language: python
python:
  - "3.5"
notifications:
  email: false

before_install:
  - sudo apt-get update
  - sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran libhdf5-serial-dev

install:

  - pip install -r requirements-dev.txt
  - pip install -e .

script:
    - tox
